```{r, fig.height=8,fig.width=10,echo=F,warning=F}
suppressWarnings(source('util.R'))

df <- '../_data/logdf/*csv' %>% Sys.glob %>% lapply(fread) %>% rbindlist
df[,date:=parse_date_time(Datetime,"ymdHMS") %>% date]
df.mostRecent <- df[, .SD[which.max(date)],by=Filesystem]

ggplot(df, aes(date, Usage)) +
    geom_line(aes(color=Filesystem), na.rm=T) +
    ggtitle("Filesystem Usage (%)") +
    geom_text(data=df.mostRecent, aes(label=Usage, color=Filesystem),  hjust = 0.9, vjust = -0.6, na.rm=T, size=7) +
    theme(text = element_text(size=20))

ggplot(df, aes(x=date, y=UsageT)) +
    geom_line(aes(color=Filesystem), na.rm=T) +
    ggtitle("Filesystem Usage (Terabytes)") +
    geom_text(data=df.mostRecent, aes(label=UsageT, color=Filesystem),  hjust = 0.9, vjust = -0.6, na.rm=T, size=7) +
    ylim(0,40) +
    theme(text = element_text(size=20))

```

```{r, results='asis', echo=F}
source('util.R')

dirsizes <- '../_data/logdirsizes/*csv' %>% Sys.glob %>% lapply(fread) %>% rbindlist
dirsizes[,date:=parse_date_time(Datetime,"ymdHMS") %>% date]
dirsizes[,Date:= format(date,format="%y-%m-%d")]
setorder(dirsizes, -date)
cols <- c("Date", "Directory", "SizeG", "deltaG")


for (numPeriods in c(1,4,8,12)) {
  ## cat("# Directory Size Changes (", numPeriods, " Periods)\n", sep="")
  for (rootDir in readLines("../_config/dirs.txt", encoding="UTF-8")) {
    rootDir <- stripHost(rootDir)
    if (numPeriods == 1) {
      cat("## ", rootDir, " biggest changes in previous week\n")
    }
    else {
      cat("## ", rootDir, " biggest changes in previous ", numPeriods, " weeks\n")
    }
    dirsizes[!Directory %like% "Trash" & Directory %like% rootDir
           , deltaG:=SizeG - shift(SizeG,numPeriods,type="lead")
           , by=Directory]
    dirsizes[order(-date,-deltaG), ..cols] %>% head(5) %>% printTable
    dirsizes[order(-date,deltaG), ..cols] %>% head(5) %>% printTable
  }
}
```

```{r, results='asis', echo=F, warning=F}
source('util.R')

setorder(dirsizes, -date, -SizeG)
cols <- c("Date", "Directory", "SizeG")

for (rootDir in readLines("../_config/dirs.txt", encoding="UTF-8")) {
    rootDir <- stripHost(rootDir)
    cat("## ", rootDir, " largest directories \n")
    dirsizes[Directory %like% rootDir, ..cols][1:6] %>% printTable
}
```

```{r, results='asis', echo=F, warning=F}
library(magrittr, quietly=TRUE)

cat("## Largest Home Directories\n")
dirsizes[Directory %like% "home/\\w+$", ..cols][1:10] %>% printTable

cat("## Largest Project Directories\n")
dirsizes[Directory %like% "projects/\\w+$", ..cols][1:10] %>% printTable

cat("## Largest Collaborators Directories\n")
dirsizes[Directory %like% "Collaborators/\\w+$", ..cols][1:10] %>% printTable
```
