 ```{r, fig.height=8,fig.width=10,echo=F}
library(ggplot2, quietly=TRUE)
source('util.R')
d <- df_from_files('../logdf.dir/*csv')
#last_date_d <- filter(d, Datetime==max(Datetime))
last_date_d <- group_by(d, Filesystem) %>% filter(Datetime==max(Datetime)) %>% ungroup()
min_date_d <- group_by(d, Filesystem) %>% filter(Datetime==min(Datetime)) %>% ungroup()
#min_date_d <- filter(d, Datetime==min(Datetime))

ggplot(d, aes(Datetime, Usage)) + 
    geom_line(aes(color=Filesystem), na.rm=T) +
    scale_y_continuous(breaks=seq(0,100,by=5), labels=function(x){sprintf("%s%%",x)}) + 
    xlab("") +
    ylab("") +
    ggtitle("Filesystem Usage") + 
    theme(text = element_text(size=20)) +
    geom_text(data=min_date_d, aes(label=Filesystem, color=Filesystem),  hjust = 0.0, vjust = -0.3) +
    geom_text(data=last_date_d, aes(label=Usage, color=Filesystem),  hjust = 0.9, vjust = -0.3, na.rm=T) +
    theme(legend.position="none")
```

```{r, results='asis', echo=F}
source('util.R')
for (i in readLines("../DIRS", encoding="UTF-8")) {
    cat("# ", i, "\n")
    print_week_changes(i)
}
```
