#!/bin/bash

logdir="$(dirname $0)/logbigfiles.dir"
mkdir -p $logdir

logfilename() {
    datestamp=$(date +"%Y%m%d")
    prefix=$(echo $1 | sed 's,\/,_,g' | sed 's,_$,,' | sed 's,^_,,')
    logfile="${prefix}-bigfiles-${datestamp}.csv"
    echo "$logdir/$logfile"
}

cmd="$(dirname $0)/scripts/bigfiles $@ > $(logfilename $1)"
echo "Running:"
echo "$cmd" >&2
eval "$cmd"
