#!/bin/bash -eu

SCRIPT=$(readlink -m $(type -p $0))
SCRIPTDIR=$(dirname $SCRIPT)

usage() {
    cat <<EOF
    Usage:

        $(basename $0) <dir> [depth]

EOF
}

logfilename() {
    local logdir=$SCRIPTDIR/logdirsizes.dir
    local datestamp=$(date +"%Y%m%d")
    local prefix=$(echo $1 | sed 's,\/,_,g' | sed 's,_$,,' | sed 's,^_,,')
    local logfile="${prefix}-dirsizes-$2-${datestamp}.csv"
    mkdir -p $logdir
    echo "$logdir/$logfile"
}

[[ $1 == "-h" || $1 == "--help" || $# -lt 1 ]] && { usage; exit 1; }

dir=$(readlink -f $1)
depth=1
[ -n "$2" ] && depth=$2

#results=$(du --time -b --max-depth $depth $dir |  \
    #sort -n | \
    #awk '{ print strftime("%Y-%m-%d %H:%M:%S") ", " $1 ", " $1/1024/1024/1024 ", " $4 ", " $2 " " $3 }' | \
    #head -n -1 )
results=$(du --time -b --max-depth $depth $dir |  \
    sort -n | \
    awk '{ print strftime("%Y-%m-%d %H:%M:%S") ", " $1 ", " $1/1024/1024/1024 ", " $4 ", " $2 " " $3 }' | \
    head -n -1 )

log=$(logfilename $1 $depth)
if [ -n "$results" ]; then
    #echo "Datetime, Size, Directory, Last Modified,  Owner" > $log
    echo "Datetime, Size, SizeG, Directory, Last Modified" > $log
    echo "$results" >> $log
else
    >&2 echo "No output found for $dir" 
    touch $log
fi
