#!/bin/sh -e

logdir="$(dirname $0)/logdirsizes.dir"
mkdir -p $logdir

logfilename() {
    datestamp=$(date +"%Y%m%d")
    prefix=$(echo $1 | sed 's,\/,_,g' | sed 's,_$,,' | sed 's,^_,,')
    logfile="${prefix}-dirsizes-$2-${datestamp}.csv"
    echo "$logdir/$logfile"
}

depth=1
[ -n "$2" ] && depth=$2

cmd="$(dirname $0)/scripts/dirsizes "$@" > $(logfilename $1 $depth)"
echo "$cmd" >&2
eval "$cmd"
