#!/bin/sh

SCRIPT=$(readlink -m $(type -p $0))
SCRIPT_DIR=$(dirname ${SCRIPT})      
CONFIGFILE=$(readlink -f $SCRIPT_DIR/config/dirs.txt)

usage() {
    cat <<EOF
Usage:

    $(basename $0) 

Prints percent usage for each filesystem listed in 
"$CONFIGFILE".

EOF
}

dfcmd() {
    local _dir=$1
    local _cmd
    read -d '' _cmd << EOF || true
df -P $_dir | sed -n '2p' | awk '{ print \$5 }' | sed 's/%//g'
EOF
    echo $_cmd
}

[[ $1 == "-h" || $1 == "--help" ]] && { usage; exit 1; }

if [ ! -f "$CONFIGFILE" ]; then
    echo "Set $CONFIGFILE first"
    exit 1
fi

date=("$(date +"%Y-%m-%d %H:%M:%S")")
echo "Datetime, Filesystem, Usage"
while read line; do
    IFS=":" read server remotepath <<< "$line"
    if [ -n "${remotepath-}" ]; then  
        cmd=$(dfcmd $remotepath)
        printf "%s, %s, %s\n" "${date[@]}" $remotepath $(ssh $server "$cmd")
    else
        cmd=$(dfcmd $line)
        printf "%s, %s, %s\n" "${date[@]}" $line $(eval "$cmd")
    fi
done <$CONFIGFILE
