#!/bin/bash

usage() {
    cat <<EOF
    Usage:

        $(basename $0) <dir>

    Finds and prints details for all files > 300M in <dir>

EOF
}

if [[ $1 == "-h" || $1 == "--help" ]]; then
    usage
    exit 0
fi

if [[ $# < 1 ]]; then
    usage >&2
    exit 1
fi

result=$(find $1 -type f -size +300000k -exec stat -c "%s, %n, %.19y, %.19x, %U" {} \; \
    | xargs -I{} echo $(date +"%Y-%m-%d %H:%M:%S"), {} \
    | sort -t, -n -k2)
if [ -n "$result" ]; then
    echo "Datetime, Size, Filename, Last Modified, Last Accessed, Owner"
    echo "$result"
else
    >&2 echo "No results found for $1"
fi
